#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "pymupdf>=1.24",
# ]
# ///
"""
extract-subexhibits.py
Reads exhibit-manifest.txt (generated by LaTeX) and creates cropped sub-exhibits.
"""

import argparse
import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from _redactions import apply_pdf_redactions, parse_redactions

try:
  import fitz  # PyMuPDF
except ModuleNotFoundError:
  fitz = None

ROOT = Path(__file__).resolve().parent
MANIFEST = ROOT / "exhibit-manifest.txt"
GENERATED_ROOT = ROOT / "Exhibits/_Generated"
DEFAULT_OUTPUT_DIR = GENERATED_ROOT

def parse_pages(pages_spec, page_count):
  """Parse 1-based page specs like "all", "6-8", or "5,74-80"."""
  pages_spec = pages_spec.strip()
  if pages_spec.lower() == "all":
    return list(range(page_count))

  page_nums = []
  seen = set()
  for part in pages_spec.split(","):
    token = part.strip()
    if not token:
      continue

    range_match = re.fullmatch(r"(\d+)\s*-\s*(\d+)", token)
    if range_match:
      start = int(range_match.group(1))
      end = int(range_match.group(2))
      if end < start:
        start, end = end, start
      candidates = range(start, end + 1)
    elif token.isdigit():
      candidates = [int(token)]
    else:
      print(f"Warning: ignoring unsupported page token '{token}'")
      continue

    for page in candidates:
      page_num = page - 1
      if page_num < 0 or page_num >= page_count:
        print(f"Warning: page {page} is outside source range 1-{page_count}")
        continue
      if page_num not in seen:
        seen.add(page_num)
        page_nums.append(page_num)

  if not page_nums:
    print(f"Warning: no valid pages found in '{pages_spec}'; using page 1")
    return [0]

  return page_nums

def parse_manifest(manifest_path):
  exhibits = {}
  with open(manifest_path, "r", encoding="utf-8") as f:
    for line in f:
      if not line.strip():
        continue
      parts = [p.strip() for p in line.split("|")]
      if len(parts) < 5:
        print(f"Warning: malformed manifest line skipped: {line.rstrip()}")
        continue
      sub_id, source, pages = parts[:3]
      crop = "|".join(parts[3:-1]).strip()
      label = parts[-1]
      exhibits[sub_id] = {
        "source": source,
        "pages": pages,
        "crop": crop,
        "label": label,
      }
  return exhibits

def default_redactions_path(manifest_path):
  candidate = ROOT / "REDACTIONS.txt"
  return candidate if candidate.exists() else None

def extract_subexhibit(sub_id, spec, redactions, output_dir):
  src_path = ROOT / spec["source"]
  if not src_path.exists():
    print(f"Warning: Source not found: {src_path}")
    return

  pages_spec = spec["pages"]
  crop_spec = spec["crop"]

  if fitz is None or crop_spec.startswith("trim:"):
    extract_pages_with_poppler(sub_id, src_path, pages_spec, crop_spec, output_dir)
    apply_pdf_redactions(output_dir / f"exhibit-{sub_id}.pdf", redactions)
    return

  doc = fitz.open(src_path)
  new_doc = fitz.open()

  page_nums = parse_pages(pages_spec, len(doc))

  for page_num in page_nums:
    page = doc[page_num]

    if crop_spec == "full":
      new_doc.insert_pdf(doc, from_page=page_num, to_page=page_num)
    elif crop_spec.startswith("text:"):
      pattern = crop_spec[5:]
      areas = page.search_for(pattern, quads=False)
      if areas:
        # Take the first matching area and add some padding
        rect = areas[0]
        rect.x0 -= 10
        rect.y0 -= 10
        rect.x1 += 10
        rect.y1 += 10
        # Create new page with cropped content
        new_page = new_doc.new_page(width=rect.width, height=rect.height)
        new_page.show_pdf_page(new_page.rect, doc, page_num, clip=rect)
      else:
        print(f"No match for pattern '{pattern}' on page {page_num+1}")
        new_doc.insert_pdf(doc, from_page=page_num, to_page=page_num)
    else:
      new_doc.insert_pdf(doc, from_page=page_num, to_page=page_num)

  out_path = output_dir / f"exhibit-{sub_id}.pdf"
  new_doc.save(out_path)
  new_doc.close()
  print(f"Created: {out_path}")
  apply_pdf_redactions(out_path, redactions)

def extract_pages_with_poppler(sub_id, src_path, pages_spec, crop_spec, output_dir):
  if crop_spec != "full" and not crop_spec.startswith("trim:"):
    print(f"Warning: PyMuPDF is unavailable; extracting full pages for {sub_id}")

  page_count = len_pdf_with_pdfinfo(src_path)
  page_nums = parse_pages(pages_spec, page_count)
  out_path = output_dir / f"exhibit-{sub_id}.pdf"

  with tempfile.TemporaryDirectory() as tmp:
    tmp_path = Path(tmp)
    page_files = []
    for page_num in page_nums:
      page = page_num + 1
      pattern = tmp_path / f"{sub_id}-{page:04d}-%d.pdf"
      subprocess.run(
        ["pdfseparate", "-f", str(page), "-l", str(page), str(src_path), str(pattern)],
        check=True,
      )
      page_file = tmp_path / f"{sub_id}-{page:04d}-{page}.pdf"
      page_files.append(page_file)

    combined_path = tmp_path / f"{sub_id}-combined.pdf"
    if len(page_files) == 1:
      shutil.copyfile(page_files[0], combined_path)
    else:
      subprocess.run(
        ["pdfunite", *[str(path) for path in page_files], str(combined_path)],
        check=True,
      )

    if crop_spec.startswith("trim:"):
      trim_spec, paper_spec = parse_trim_spec(crop_spec)
      crop_source_path = combined_path
      if fitz is not None:
        crop_source_path = sanitize_pdf_outside_trim(
          combined_path,
          trim_spec,
          tmp_path / f"{sub_id}-trim-sanitized.pdf",
        )
      command = [
        "pdfjam",
        "--outfile", str(out_path),
      ]
      if paper_spec:
        command.extend(["--papersize", paper_spec])
      command.extend(
        [
          "--trim", trim_spec,
          "--clip", "true",
          str(crop_source_path),
        ]
      )
      subprocess.run(command, check=True)
    else:
      shutil.copyfile(combined_path, out_path)

  print(f"Created: {out_path}")

def sanitize_pdf_outside_trim(src_path, trim_spec, out_path):
  left, bottom, right, top = parse_trim_values(trim_spec)
  doc = fitz.open(src_path)

  for page in doc:
    page_rect = page.rect
    visible = fitz.Rect(
      left,
      top,
      page_rect.width - right,
      page_rect.height - bottom,
    )
    redaction_rects = outside_rects(page_rect, visible)
    if not redaction_rects:
      continue

    for rect in redaction_rects:
      page.add_redact_annot(rect, fill=(1, 1, 1))
    page.apply_redactions()

  doc.save(out_path, garbage=4, deflate=True)
  doc.close()
  return out_path

def parse_trim_values(trim_spec):
  parts = trim_spec.split()
  if len(parts) != 4:
    raise ValueError(f"Expected four trim values, got '{trim_spec}'")
  return tuple(float(part) for part in parts)

def outside_rects(page_rect, visible):
  visible = visible & page_rect
  if visible.is_empty:
    return [page_rect]

  rects = []
  candidates = [
    fitz.Rect(page_rect.x0, page_rect.y0, visible.x0, page_rect.y1),
    fitz.Rect(visible.x1, page_rect.y0, page_rect.x1, page_rect.y1),
    fitz.Rect(visible.x0, page_rect.y0, visible.x1, visible.y0),
    fitz.Rect(visible.x0, visible.y1, visible.x1, page_rect.y1),
  ]
  for rect in candidates:
    if rect.width > 0.01 and rect.height > 0.01:
      rects.append(rect)
  return rects

def parse_trim_spec(crop_spec):
  """Parse crop specs like "trim:0 0 0 270" or "trim:0 0 0 270;paper:612 522"."""
  trim_spec = crop_spec[5:].strip()
  paper_spec = None
  paper_match = re.search(
    r";\s*paper:\s*([0-9.]+)\s+([0-9.]+)\s*$",
    trim_spec,
  )
  if paper_match:
    width, height = paper_match.groups()
    paper_spec = f"{{{width}pt,{height}pt}}"
    trim_spec = trim_spec[:paper_match.start()].strip()

  return trim_spec, paper_spec

def len_pdf_with_pdfinfo(src_path):
  result = subprocess.run(
    ["pdfinfo", str(src_path)],
    check=True,
    text=True,
    capture_output=True,
  )
  for line in result.stdout.splitlines():
    if line.startswith("Pages:"):
      return int(line.split(":", 1)[1].strip())
  raise RuntimeError(f"Could not read page count from pdfinfo output for {src_path}")

def resolve_root_path(path_text):
  path = Path(path_text)
  if not path.is_absolute():
    path = ROOT / path
  return path

def display_path(path):
  try:
    return path.relative_to(ROOT).as_posix()
  except ValueError:
    return path.as_posix()

def update_generated_index(output_dir, manifest_path, tex_source, exhibits):
  GENERATED_ROOT.mkdir(parents=True, exist_ok=True)
  index_path = GENERATED_ROOT / "index.json"

  if index_path.exists():
    try:
      data = json.loads(index_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
      data = {}
  else:
    data = {}

  documents = data.setdefault("documents", {})

  if tex_source:
    tex_path = resolve_root_path(tex_source)
    document_key = display_path(tex_path)
  else:
    document_key = f"manifest:{display_path(manifest_path)}"

  manifest_copy = output_dir / "exhibit-manifest.txt"
  shutil.copyfile(manifest_path, manifest_copy)

  documents[document_key] = {
    "generated_dir": display_path(output_dir),
    "manifest": display_path(manifest_copy),
    "exhibit_count": len(exhibits),
    "exhibits": list(exhibits.keys()),
  }

  index_path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")

def prune_stale_output(output_dir, exhibits):
  expected = {f"exhibit-{sub_id}.pdf" for sub_id in exhibits}
  for pdf_path in output_dir.glob("exhibit-*.pdf"):
    if pdf_path.name not in expected:
      pdf_path.unlink()
      print(f"Removed stale generated exhibit: {pdf_path}")

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument(
    "--manifest",
    default=str(MANIFEST),
    help="Path to the exhibit manifest generated by LaTeX.",
  )
  parser.add_argument(
    "--redactions",
    help="Path to a newline-delimited list of literal text to redact.",
  )
  parser.add_argument(
    "--output-dir",
    default=str(DEFAULT_OUTPUT_DIR),
    help="Directory where generated sub-exhibit PDFs should be written.",
  )
  parser.add_argument(
    "--tex-source",
    help="Source .tex file that produced this manifest, used for _Generated/index.json.",
  )
  args = parser.parse_args()

  manifest_path = resolve_root_path(args.manifest)

  if not manifest_path.exists():
    print(f"No manifest found at {manifest_path}. Skipping extraction.")
    return

  output_dir = resolve_root_path(args.output_dir)
  output_dir.mkdir(parents=True, exist_ok=True)
  print(f"Writing generated exhibits to {output_dir}")

  redactions_path = Path(args.redactions) if args.redactions else default_redactions_path(manifest_path)
  if redactions_path and not redactions_path.is_absolute():
    redactions_path = ROOT / redactions_path
  redactions = parse_redactions(redactions_path)
  if redactions:
    print(f"Loaded {len(redactions)} redaction term(s) from {redactions_path}")

  exhibits = parse_manifest(manifest_path)
  update_generated_index(output_dir, manifest_path, args.tex_source, exhibits)
  prune_stale_output(output_dir, exhibits)
  for sub_id, spec in exhibits.items():
    extract_subexhibit(sub_id, spec, redactions, output_dir)

if __name__ == "__main__":
  main()
